### ISSUE TITLE
Outdated test dependencies

### ISSUE THREAD

**Issue by frenzymadness** [blambright/qstylizer#11]
Hello.

It seems that some test dependencies defined in setup.cfg are pretty old (pytest, pytest-mock) even the tests work well with the latest versions. It also seems that some of them are not needed (pytest-cov). Also, having tox in the list of test dependencies means that tox is installed inside tox virtual environments. Moreover, Travis config uses tox environment not defined in the tox.ini (py35). `pytest-runner` is [deprecated](https://pypi.org/project/pytest-runner/) . Also, AFAIK, pytest-xdist needs to be enabled via `-n auto` CLI argument so right now it's not used as well.

Let me know if you want me to prepare a PR for these issues.

**Comment by blambright** [comment]
Updated the test dependencies. thanks for the heads up! and sorry for the delay
