### ISSUE TITLE
[Question] Support for styling single objects

### ISSUE THREAD

**Issue by DanielSvindseth** [blambright/qstylizer#14]
PySide6 supports applying styles to a single item/object of a certain name:

`QPushButton#myButton { background-color: blue }`

How can I accomplish this with qstylizer? I cannot find anything about it in the docs.

**Comment by blambright** [comment]
You would have to use this approach:
```python
>>> css = qstylizer.style.StyleSheet()
>>> css["QPushButton#myButton"].backgroundColor.setValue("red");
>>> print(css.toString())
QPushButton#myButton {
    background-color: red;
}
```

**Comment by blambright** [comment]
This also works:
```python
>>> css.QPushButton["#myButton"].backgroundColor.setValue("red")
```
