### ISSUE TITLE
Question: Merging stylesheets

### ISSUE THREAD

**Issue by hhslepicka** [blambright/qstylizer#4]
Is there a utility at the library to merge Stylesheet objects?

**Comment by hhslepicka** [comment]
Here is a gist of my attempt to that... https://gist.github.com/hhslepicka/e6a5e452a14d7be77e9cb4b8831ba1a0
What is weird is that after updating the style 1 with style 2, the property works fine but toString reports a wrong value.

**Comment by blambright** [comment]
I have a fix for this. Just need to test it a little more. If all goes well I can release it tomorrow

**Comment by hhslepicka** [comment]
Thanks @blambright

**Comment by hhslepicka** [comment]
also, I have many custom widgets and I reference them at my stylesheet but at the Stylesheet object I can only see the regular QWidgets accessible via dot. Is that expected? (It is not a big deal for me)

**Comment by blambright** [comment]
Ah yeah, that's expected. I use descriptors to get a list accessible via the dot. might be possible to get a custom widget to show up in there but i'm not sure

**Comment by hhslepicka** [comment]
@blambright for now that is not a big deal... thanks for the fast response! 👍

**Comment by blambright** [comment]
This was released in version 0.1.9
