### ISSUE TITLE
Unit tests fail on Python 2.7

### ISSUE THREAD

**Issue by buddly27** [blambright/qstylizer#7]
Arguments are missing for [super](https://docs.python.org/2/library/functions.html#super) in [qstylizer.parser.QSSParser.parse_declaration](https://github.com/blambright/qstylizer/blob/master/qstylizer/parser.py#L9).

```python
    def parse_declaration(self, tokens):
>       declaration = super().parse_declaration(tokens)
E       TypeError: super() takes at least 1 argument (0 given)
```

**Comment by blambright** [comment]
Released with qstylizer 0.1.10
